
#define INITIAL_PROMPT "Welcome to YOURS BANK !\n Who are you?\n1. Admin\t2. Customer\nPress any other number to exit\n Enter the number corresponding to the choice!"


// ===============================================ADMIN SPECIFIC TEXT=============================================================================================================================

// LOGIN WELCOME
#define ADMIN_LOGIN_WELCOME "Welcome dear admin!\nEnter your credentials!"
#define ADMIN_LOGIN_SUCCESS "Welcome Sir!"

// ADMIN MENU
#define ADMIN_MENU "1. Get Customer Details\n2. Get Account Details\n3. Get Transaction details\n4. Add Account\n5. Delete Account\n6. Modify Customer Information\nPress any other key to logout"

// ADD CUSTOMER
#define ADMIN_ADD_CUSTOMER_PRIMARY "Enter the details for the primary customer\n"
#define ADMIN_ADD_CUSTOMER_SECONDARY "Enter the details for the secondary customer\n"
#define ADMIN_ADD_CUSTOMER_NAME "Enter customer's name?"
#define ADMIN_ADD_CUSTOMER_GENDER "Enter customer's gender?\nEnter M for male, F for female and O for others"
#define ADMIN_ADD_CUSTOMER_AGE "Enter customer's age?"
#define ADMIN_ADD_CUSTOMER_AUTOGEN_LOGIN "The autogenerated login ID for the customer is : "
#define AUTOGEN_PASSWORD "passward123" // append to end of next string macro
#define ADMIN_ADD_CUSTOMER_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define ADMIN_ADD_CUSTOMER_WRONG_GENDER "Invalid wrong gender choice!\n You'll now be redirected to the main menu!^"

// ADD ACCOUNT
#define ADMIN_ADD_ACCOUNT_TYPE "What type of account is to be created? Enter 1 for regular account and 2 for joint account"
#define ADMIN_ADD_ACCOUNT_NUMBER "The newly created account's number is :"

// DELETE ACCOUNT
#define ADMIN_DEL_ACCOUNT_NO "Enter the account number of the account you want to delete?"
#define ADMIN_DEL_ACCOUNT_SUCCESS "This account has been successfully deleted\nRedirecting you to the main menu ...^"
#define ADMIN_DEL_ACCOUNT_FAILURE "This account cannot be deleted since it still has some money\nRedirecting you to the main menu ...^"

// MODIFY CUSTOMER INFO
#define ADMIN_MOD_CUSTOMER_ID "Enter the ID of the customer who's information you want to edit"
#define ADMIN_MOD_CUSTOMER_MENU "Which information would you like to modify?\n1. Name 2. Age 3. Gender \nPress any other key to cancel"
#define ADMIN_MOD_CUSTOMER_NEW_NAME "Enter the updated value for name?"
#define ADMIN_MOD_CUSTOMER_NEW_GENDER "Enter the updated value for gender?"
#define ADMIN_MOD_CUSTOMER_NEW_AGE "Enter the updated value for age?"

#define ADMIN_MOD_CUSTOMER_SUCCESS "The information is successfully modified!\nYou'll now be redirected to the main menu!^"

#define ADMIN_LOGOUT "Logging you out! $"


// =============================================== CUSTOMER SPECIFIC TEXT===============================================================

// LOGIN WELCOME
#define CUSTOMER_LOGIN_WELCOME "Welcome dear customer! Enter your credentials to gain access to your account!"
#define CUSTOMER_LOGIN_SUCCESS "Welcome beloved customer!"

#define CUSTOMER_LOGOUT "Logging you out now !$"

// ADMIN MENU
#define CUSTOMER_MENU "1. Get Customer Details\n2. Deposit Money\n3. Withdraw Money\n4. Get Balance\n5. Get Transaction information\n6. Change Password\nPress any other key to logout"

#define ACCOUNT_DEACTIVATED "Your account is deactivated!^"

#define DEPOSIT_AMOUNT "Enter the amount you want to deposit"
#define DEPOSIT_AMOUNT_INVALID "Invalid amount!^"
#define DEPOSIT_AMOUNT_SUCCESS "Amount is SUCCESSFULLY added to the account!^"

#define WITHDRAW_AMOUNT "Enter the amount you want to withdraw"
#define WITHDRAW_AMOUNT_INVALID "Invalid input or insuffient balanace^"
#define WITHDRAW_AMOUNT_SUCCESS "Amount is SUCCESSFULLY withdraw from your account!^"

#define PASSWORD_CHANGE_OLD_PASS "Enter your old password"
#define PASSWORD_CHANGE_OLD_PASS_INVALID "Wrong passward"
#define PASSWORD_CHANGE_NEW_PASS "Enter the new password"
#define PASSWORD_CHANGE_NEW_PASS_RE "Re-enter the new password"
#define PASSWORD_CHANGE_NEW_PASS_INVALID "The new password and the reentered passwords don't seem to pass!^"
#define PASSWORD_CHANGE_SUCCESS "Password successfully changed!^"

// ======================================================= COMMON TEXT ============================================================================

// LOGIN
#define LOGIN_ID "Enter your login ID"
#define PASSWORD "Enter your password \n# "
#define INVALID_LOGIN "The login ID specified doesn't exist!$"
#define INVALID_PASSWORD "The password specified doesn't match!$"
#define SALT_BAE "666"

// GET ACCOUNT DETAILS
#define GET_ACCOUNT_NUMBER "Enter the account number"
#define GET_CUSTOMER_ID "Enter the customer ID "

#define ERRON_INPUT_FOR_NUMBER "Invalid input!\n Please enter input in number only \nYou'll now be redirected to the main menu!^"

#define INVALID_MENU_CHOICE "Invalid menu choice\nYou'll now be redirected to the main menu!^"

#define CUSTOMER_ID_DOESNT_EXIT "No customer could be found for the given ID"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIT "No customer could be found for the given login ID$"

#define ACCOUNT_ID_DOESNT_EXIT "No account could be found for the given account number"

#define TRANSACTIONS_NOT_FOUND "No transactions were performed on this account by the customer!^"


//=================================================================================================================================
#define ACCOUNT_FILE "./records/account.bank"
#define CUSTOMER_FILE "./records/customer.bank"
#define TRANSACTION_FILE "./records/transactions.bank"


